wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.7
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1694161315.71977
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.8.7
      5: 0.15.10
      8:
      - 2
      - 3
      - 5
epoch:
  desc: null
  value: 30
spiking_step:
  desc: null
  value: 25
lr:
  desc: null
  value: 0.002
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
batch_size:
  desc: null
  value: 2
classes:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
device:
  desc: null
  value: cuda:0
log:
  desc: null
  value: true
project:
  desc: null
  value: DaconDomainAdaptive
log_name:
  desc: null
  value: SpikingUNet
root:
  desc: null
  value: D:/Side/Dacon/DomainAdaptive/dataset
run_type:
  desc: null
  value:
  - train
  - val
  - test
